### ISSUE TITLE
一些疑惑，请教一下

### ISSUE THREAD

**Issue by HaveF** [jysperm/leancloud-graphql#1]
感谢精子提供这个repo

1. 客户端原来是使用leancloud的api和leancloud进行通信，比如下面代码

  ```js
    const TestObject = AV.Object.extend('TestObject');
    const testObject = new TestObject();
    await testObject.save({ words: 'Hello World!' });
```

会往`https://api.leancloud.cn/1.1/classes/TestObject?`post一些数据，post的过程中客户端的request header会带一些东西，主要是分成两部分，第一部分是客户端的信息，比如User-Agent, Origin等等，第二部分是AV相关信息，比如X-LC-UA, X-LC-Sign, X-LC-Id等等。
现在是怎么处理的，我没有看太懂
第二部分是通过设置`X-LC-Session`，然后云引擎和云存储交互，客户端什么都不用管
第一部分信息是通过

```js
const parseLeancloudHeaders = require('leanengine/middleware/parse-leancloud-headers');

app.use(parseLeancloudHeaders(AV, {restrict: false}));
```

传递到后面去了吗？

2. 有计划使用apollo graphql server吗？ http://dev.apollodata.com/tools/  
还是只用`"express-graphql"` 做个good enough的版本就可以了?

非常感谢！

**Comment by jysperm** [comment]
感谢关注，目前该项目还属于实验性阶段，还有诸多不足。

> X-LC-Id, X-LC-Sign 等信息是如何传递的？

在使用 JavaScript SDK 的时候，所有应用都在向 api.leancloud.cn 发请求，所以需要 X-LC-Id 来区别不同的易用。而 leancloud-graphql 的使用方法是部署在你自己的云引擎上，绑定一个二级域名（如 jysperm.leanapp.cn ），然后客户端通过这个二级域名来访问，因此不需要 X-LC-Id 来区别应用。

用 parseLeancloudHeaders 只是为了取出 X-LC-Session，这个代表用户的登录状态，用来区分这个请求的权限。不过后来我又对这个部分的代码做了调整，简单期间，我没有再使用 parseLeancloudHeaders 了，而是简单地读取 X-LC-Session 这个头（ https://github.com/jysperm/leancloud-graphql/blob/770263570faf855603e642c880f53b53cd36f5fc/middleware.js#L31 ）

> 有计划使用apollo graphql server吗？

我还没了解过这个包，回头我会去调研一下。但其实这并不是 leancloud-graphql 最核心的工作，如果你要使用 apollo 的话，可以用 README 中介绍的方法（ https://github.com/jysperm/leancloud-graphql#获取-graphqlschema ），获取到 GraphQLSchema 之后传递给 apollo。

**Comment by HaveF** [comment]
感谢精子回复:grin:

关于X-LC-Id我懂了。

客户端的信息，比如User-Agent, Origin等等，在使用js sdk的时候，这些信息应该会被lean cloud记录吧？但如果是使用leancloud-graphql，这一部分信息是不是就没了？有办法，有必要把这些信息都保留转发给api.leancloud.cn吗？

当然现在`api统计`里面好像也没看到这一类信息

**Comment by jysperm** [comment]
使用了 leancloud-graphql 之后就相当于是云引擎上的这个应用在帮你调用云存储，这些 Header 也是由这个云引擎应用发送的，而不是客户端发送的。
